import type {Metadata} from 'next';
import Header from '../components/Header';
import Footer from '../components/Footer';
import ContactForm from '../components/ContactForm';
import WorkShare from '../components/WorkShare';
import './work.css';
const base='/media/realizacie/';
const title='Realizácie a bezplatná kontrola okien | LION Company';
const description='Skutočné fotografie a videá zo servisu okien. Výmena kovania a tesnení, sieťky a žalúzie. Bezplatná kontrola v Bratislave a okolí.';
export const metadata:Metadata={title,description,alternates:{canonical:'https://lion-company.sk/realizacie'},openGraph:{title,description,url:'https://lion-company.sk/realizacie',type:'website',locale:'sk_SK',images:[{url:'https://lion-company.sk/media/realizacie/okno-po-servise.webp',width:1024,height:1024,alt:'Otvorené okno po servisnom zásahu LION Company'}]},twitter:{card:'summary_large_image',title,description,images:['https://lion-company.sk/media/realizacie/okno-po-servise.webp']}};
function Clip({name,title,description}:{name:string;title:string;description:string}){return <figure className="work-clip"><video controls playsInline preload="none" poster={`${base}${name}-poster.jpg`} aria-label={title}><source src={`${base}${name}.mp4`} type="video/mp4"/>Váš prehliadač nepodporuje prehrávanie videa. <a href={`${base}${name}.mp4`}>Stiahnuť video</a></video><figcaption><strong>{title}</strong><p>{description}</p><small>Skutočný záznam zo zákazky · bez zvuku</small></figcaption></figure>}
function Shot({name,caption}:{name:string;caption:string}){return <figure><a href={`${base}${name}.webp`} target="_blank" rel="noopener noreferrer" aria-label={`Zväčšiť: ${caption}`}><img src={`${base}${name}.webp`} alt={caption} loading="lazy" width={900} height={1200}/></a><figcaption>{caption}</figcaption></figure>}
export default function Page(){return <><Header/><main className="work-page">
 <section className="wrap work-intro"><div><p className="breadcrumbs"><a href="/">Domov</a> / Realizácie</p><span className="eyebrow">NAŠA PRÁCA. VAŠE POHODLIE.</span><h1>Okná majú<br/>ďalšiu <em>šancu.</em></h1><p className="work-lead">Od opotrebovaného tesnenia po nové kovanie. Pozrite si detaily našich zásahov aj možnosti, ako zlepšiť vetranie, súkromie a pohodlie doma.</p><div className="actions"><a href="#obhliadka" className="btn">Bezplatná kontrola okien ↗</a><a href="#kovanie" className="link">Pozrieť ukážky práce ↓</a></div><p className="work-area">Bratislava a okolie · 0945 454 277</p></div><figure className="work-cover"><img src={`${base}okno-po-servise.webp`} alt="Otvorené biele okno po servise, pohľad z interiéru" width={1024} height={1024} fetchPriority="high"/><figcaption>Servis a modernizácia okien / LION Company</figcaption></figure></section>
 <div className="work-jump wrap" aria-label="Sekcie realizácií"><a href="#kovanie">01 Kovanie</a><a href="#tesnenie">02 Tesnenie a korózia</a><a href="#sietky">03 Sieťky</a><a href="#tienenie">04 Tienenie</a></div>
 <section className="wrap work-section" id="kovanie"><div className="heading"><div><span className="eyebrow">01 / KOVANIE A NOVÉ MOŽNOSTI VETRANIA</span><h2>Keď zatváranie<br/>prestane ísť ľahko.</h2></div><p>Drhnutie, uvoľnený pánt alebo poškodený mechanizmus sú dôvodom na kontrolu. Posúdime, či pomôže nastavenie, výmena dielu alebo celého kovania.</p></div>
 <div className="repair-story"><Shot name="korozia-kovania" caption="PRED ZÁSAHOM / Korózia v oblasti horného pántu a kovania."/><div className="repair-story-copy"><span className="work-pill">VÝMENA A MODERNIZÁCIA</span><h3>Správne kovanie.<br/>Nová funkčnosť.</h3><p>Po výmene preveríme otváranie, zatváranie a dosadnutie krídla. Pri kompatibilnom okne môžeme doplniť mikrovetranie alebo prerobiť iba otváracie kovanie na otváravo-sklopné.</p><ul><li>Kontrola pántov, uzáverov a nastavenia</li><li>Výmena poškodených komponentov</li><li>Možnosť mikrovetrania podľa typu kovania</li><li>Posúdenie prestavby na otváravo-sklopné okno</li></ul><a className="link" href="#obhliadka">Overiť možnosti môjho okna →</a></div></div>
 <div className="video-grid"><Clip name="detail-kovania" title="Detail kovania pri servise" description="Technik ukazuje pohyblivý prvok kovania a jeho funkciu na otvorenom krídle."/><Clip name="otvaravo-sklopne-okno" title="PO ZÁSAHU / Otváranie aj sklopenie" description="Ukážka ovládania kľučkou, otvorenia a sklopnej polohy okna po modernizácii."/><Clip name="otvaravo-sklopne-dvere" title="Otváravo-sklopné balkónové dvere" description="Predvedenie otvárania a sklápacej funkcie balkónových dverí."/></div><p className="evidence-note">Fotografie poškodenia a videá funkčnosti zachytávajú rôzne servisné zásahy. Nejde o párové zábery toho istého okna.</p>
 </section>
 <section className="prevention-band" id="tesnenie"><div className="wrap work-section"><div className="heading"><div><span className="eyebrow">02 / PREVENCIA MÁ ZMYSEL</span><h2>Začalo sa tesnením.<br/>Skončilo sa výmenou kovania.</h2></div><p>Príklad z našej praxe: poškodené tesnenie prepúšťalo vlhkosť. Tá sa dostala ku kovaniu, ktoré skorodovalo, oslabilo sa a bolo potrebné ho vymeniť.</p></div><div className="damage-grid"><Shot name="skorodovany-pant" caption="Skorodovaný pánt: poškodenie viditeľné na detaile."/><Shot name="stare-tesnenie" caption="Odstránené staré tesnenie, ktoré stratilo svoju funkciu."/><Shot name="detail-ramu" caption="Detail rámu, tesnenia a kovania pred servisom."/></div><div className="prevention-message"><h3>Nenechajte malý problém vyrásť.</h3><p>Aj tesnenie a kovanie majú svoju životnosť. Včasná kontrola môže odhaliť problém skôr, než si vyžiada rozsiahlejšiu a drahšiu opravu. Pri tejto zákazke nestačila samotná výmena tesnenia — bolo potrebné riešiť aj poškodené kovanie.</p><a className="btn" href="#obhliadka">Nechám si okná skontrolovať bezplatne ↗</a></div><details className="more-work"><summary>Ďalšie detaily zo servisných zásahov</summary><div className="damage-grid"><Shot name="opotrebovane-kovanie" caption="Kontrola opotrebovaného kovania na krídle."/><Shot name="pant-pocas-servisu" caption="Pánt a rám počas servisného zásahu."/><Shot name="vymena-tesnenia" caption="Odstránenie tesnenia a príprava rámu pri výmene."/></div></details></div></section>
 <section className="wrap work-section" id="sietky"><div className="heading"><div><span className="eyebrow">03 / SIEŤKY PROTI HMYZU</span><h2>Otvorte okno.<br/><em>Hmyz nechajte vonku.</em></h2></div><p>Pevné, dverové, plisované aj rolovacie siete na mieru. Typ rámu a sieťoviny vyberieme podľa okna, spôsobu používania a vašich potrieb.</p></div><figure className="service-comparison"><img src={`${base}insect-screen-comparison.webp`} alt="Ilustračné porovnanie otvoreného okna bez siete vľavo a so sieťkou proti hmyzu vpravo" loading="lazy" width={1600} height={800}/><div className="comparison-captions"><span>PRED / Voľný vstup pre hmyz</span><span>PO / Vetranie so sieťkou</span></div><figcaption>Ilustrácia vytvorená pomocou AI. Nie je fotografiou konkrétnej realizácie.</figcaption></figure><div className="option-grid"><article><h3>Pet sieťovina</h3><p>Odolnejšia sieťovina do domácností so zvieratami. Vhodnosť posúdime podľa rámu a používania. Sieťka nie je zábranou proti pádu.</p></article><article><h3>Protipeľová sieťovina</h3><p>Možnosť hypoalergénnej, protipeľovej sieťoviny. Konkrétny materiál a jeho parametre vám predstavíme pri výbere.</p></article><article><h3>Rolovacie siete</h3><p>Sieť vysuniete, keď ju potrebujete, a zviniete do kazety. Praktické riešenie tam, kde chcete otvor ľahko uvoľniť.</p></article></div><div className="video-feature"><Clip name="dverova-siet" title="Z praxe / Dverová sieť proti hmyzu" description="Otváranie a zatváranie sieťových dverí na balkóne."/><div><h3>Riešenie sa začína zameraním.</h3><p>Skontrolujeme priestor na montáž a pomôžeme vybrať vhodnú sieťku aj spôsob otvárania.</p><a className="btn" href="#obhliadka">Dohodnúť bezplatnú obhliadku ↗</a></div></div></section>
 <section className="work-section shading-band" id="tienenie"><div className="wrap"><div className="heading"><div><span className="eyebrow">04 / SÚKROMIE A TIENENIE</span><h2>Svetlo podľa vás.<br/>Súkromie pre vás.</h2></div><p>Bez tienenia môžu byť problémom pohľady susedov, ostré slnko aj prehrievanie. Látkové rolety a lamelové žalúzie pomáhajú regulovať svetlo a súkromie.</p></div><figure className="service-comparison"><img src={`${base}blinds-comparison.webp`} alt="Ilustrácia rovnakého okna bez tienenia, s látkovou roletou a s lamelovými žalúziami" width={1600} height={800} loading="lazy"/><div className="comparison-captions three"><span>PRED / Bez tienenia</span><span>PO / Látková roleta</span><span>PO / Lamelové žalúzie</span></div><figcaption>Ilustrácia vytvorená pomocou AI. Účinok na teplotu závisí od zvoleného systému a objektu.</figcaption></figure><div className="shading-note"><h3>Prehrievanie riešime podľa objektu.</h3><p>Interiérové tienenie rieši najmä svetlo a súkromie. Ak je hlavným problémom letné teplo, posúdime aj vonkajšie žalúzie alebo rolety.</p></div><div className="video-grid two"><Clip name="lamelove-zaluzie" title="Z praxe / Lamelové žalúzie" description="Pohľad na interiérové žalúzie na balkónových dverách a priľahlom okne."/><Clip name="kontrola-okna" title="Z praxe / Kontrola okna a kovania" description="Detail otvoreného okna, uzáverov a interiérových žalúzií."/></div></div></section>
 <section className="contact-bg" id="obhliadka"><div className="wrap contact"><div><span className="eyebrow">BEZPLATNÁ KONTROLA · BRATISLAVA A OKOLIE</span><h2>Vaše okná.<br/>Náš odborný<br/><em>pohľad.</em></h2><p>Skontrolujeme stav tesnenia, kovania a nastavenie okien. Obhliadka aj cenová ponuka sú bezplatné. Prípadný servis alebo výmenu vykonáme až po odsúhlasení ceny.</p><ol className="checkup-list"><li>Nechajte nám kontakt a obec.</li><li>Dohodneme termín bezplatnej obhliadky.</li><li>Vysvetlíme stav okien a navrhneme ďalší postup.</li></ol><a href="tel:+421945454277" className="big-phone">0945 454 277 ↗</a><a className="location" href="mailto:lion_company_info@proton.me">lion_company_info@proton.me</a></div><ContactForm heading="Mám záujem o bezplatnú kontrolu" initialService="Bezplatná kontrola okien"/></div></section>
 <section className="wrap work-section"><WorkShare/><p className="services-more"><a href="https://www.facebook.com/100064733659141/photos/" target="_blank" rel="noopener noreferrer">Ďalšie fotografie na našom Facebooku ↗</a></p></section>
 </main><Footer/></>}
